# Generated by Django 4.2 on 2023-04-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_diary', models.TextField(max_length=500, null=True)),
                ('full_dialog', models.TextField(max_length=500, null=True)),
                ('prompt', models.TextField(max_length=200, null=True)),
                ('url', models.TextField(null=True)),
                ('thumbnail_url', models.TextField(null=True)),
            ],
        ),
    ]
