version: '2'
services:
  spark-master:
    image: jupyter/all-spark-notebook
    container_name: spark-master-docker
    hostname: spark-master
    ports:
      - 8080:8080
      - 7077:7077
      - 4040:4040
      - 18081:18080
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      # - NVIDIA_VISIBLE_DEVICES=0
    # command: "start-master.sh"
    # runtime: "nvidia"

  spark-worker:
    image: jupyter/all-spark-notebook
    container_name: spark-master-worker-docker
    depends_on:
      - spark-master
    ports:
      - 8080
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8080
    # command: "start-worker.sh"